color:
    when: always
    theme: default
size: short
total-size: false
indicators: false
no-symlink: false
icons:
    when: never
date: relative
blocks:
    - permission
    - size
    - date
    - git
    - name
symlink-arrow: ->
