general.import = ["~/.config/alacritty/catppuccin-mocha.toml "]

[env]
TERM = "xterm-256color"

[cursor]
blinking = ""
style = "Block"

[mouse]
hide_when_typing = true

[window]
padding.x = 14
padding.y = 14
decorations = "None"
startup_mode = "Fullscreen"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
size = 12

[[keyboard.bindings]]
key = "NumpadEnter"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "Enter"
mods = "Control|Shift"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "Equals"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control|Shift"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control|Shift"
action = "ResetFontSize"

[scrolling]
history = 10000

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"
save_to_clipboard = false
